appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: STGXnabLH1J8hBxpWd2q34qqmc7v1CjJbx6bThlSr4HfANN8AnR2HSosksQLJnuCKDiBMyuMQufaVmIM+jqiH6W9taxT/7GLBS2JoDyDnjjrPAjQuX+L/RVagvzWWAinc7JBfcYW/KNstdi8OfJawMZsjwTO6UJiQYuT17AKML8DqKqOqpJ17CJUrL7M0XwvYPFRbirTFQWYogVj90eoPLscmJLjcxyY6b1/edjmmmUW/2P3KRKmgCssIWIcmOU7yyAcb+Po12wD2P3vYaRYgztMjqp2knIH5o6iN/qHdrHvMTwR2ya8ol7YJNrIMg3l1XCpDHD45LeQ3CcwNefGpNA++RV0kM1X5m2RXfzd1fxTyFZ6XPEonGF/TIT+Ez7inLG2EH9BU8dI9/dRXfKk3O5P8UaznC+v32cf7SGghKjLo2fJN5IkH04kHr4vy9zY8gqGGRtQUMn5j4pYNPPzBOBQOu4+d9k20FKb63PIT1hodMCpK147cpEOCOWzlxu8VSshoa95FEr6VftbDogyV8Yl0NDIbdy0yAsd7zqFS52rz54b0fw2eONZCWct0fWzkYUj48TUAFQFjv/V1AYg+TfRB0vT36WWzuoO0uy3BxNH7o+ZsAZGrb08QDli6ze3oGgNrxKLFravfqFB+HJgxlhFq5RPKNKu1+LEkSVkivg=
conda_forge_output_validation: false
